world_books/WebBooks/WebBooks/urls.py
from django.contrib import admin
from django.urls import path, include
from catalog import views
from django.urls import re_path as url

urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('', views.index, name='index'),
    #path('', views.add_task, name='add_task'),
    path('admin/', admin.site.urls),
    url(r'^books/$',views.BookListView.as_view(), name ='books'),
    path('update/<int:task_id>', views.edit_task, name='edit_task'),
    path('delete/<int:task_id>', views.delete_task, name='delete_task'),
    url(r'^books/(?P<pk>\d+)$', views.BookDetailView.as_view(), name = 'book-detail'),
    url(r'^authors/$', views.AuthorListView.as_view(), name = 'authors'),
]

world_books/WebBooks/catalog/models.py
from django.db import models
from django.db.models import CharField
from django.urls import reverse

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text=" Введите жанр книги", verbose_name="Жанр книги")

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=200, help_text=" Введите язык книги", verbose_name="Язык книги")

    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=100, help_text="Введите имя автора", verbose_name="Имя автора")
    last_name = models.CharField(max_length=100, help_text="Введите фамилию автора", verbose_name="Фамилия автора")
    date_of_birth = models.DateField(help_text="Введите дату рождения", verbose_name="Дата рождения", null=True, blank=True)
    date_of_death = models.DateField(help_text="Введите дату смерти", verbose_name="Дата смерти", null=True, blank=True)

    def __str__(self):
        return self.last_name

class Book(models.Model):
    title = models.CharField(max_length=200, help_text="Введите название книги", verbose_name="Название книги")
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE, help_text="Выберите жанр для книги", verbose_name="Жанр книги", null=True)
    language = models.ForeignKey('Language', on_delete=models.CASCADE, help_text="Выберите язык для книги", verbose_name="Язык книги", null=True)
    author = models.ManyToManyField('Author', help_text="Выберите автора книги", verbose_name="Автор книги")
    summary = models.TextField(max_length=1000, help_text="Введите краткое описание книги", verbose_name="Аннотация книги")
    isbn = models.CharField(max_length=13, help_text="Должно содержать 13 символов", verbose_name="ISBN книги")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_author(self):
        return ', '.join([author.last_name for author in
                          self.author.all()])
    display_author.short_description = 'Авторы'


class Status(models.Model):
    name = models.CharField(max_length=20, help_text="Введите статус экземпляра книги", verbose_name="Статус экземпляра книги")

    def __str__(self):
        return self.name

class BookInstance(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    inv_nom = models.CharField(max_length=20, null=True, help_text="Введите инвентарный номер книги", verbose_name="Инвентарный номер книги")
    imprint = models.CharField(max_length=200, help_text="Введите издательство и год выпуска", verbose_name="Издательство")
    status = models.ForeignKey('Status', on_delete=models.CASCADE, null=True, help_text='Изменить состояние экземпляра', verbose_name="Статус экземпляра книги")
    due_back = models.DateField(null=True, blank=True, help_text="Введите конец срока статуса", verbose_name="Дата окончания статуса")

    def __str__(self):
        return '%s %s %s' %(self.inv_nom, self.book, self.status)

class Lecturer(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Course(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    lecturer = models.ForeignKey('Lecturer', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Group(models.Model):
    name = models.CharField(max_length=100)
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    students = models.ManyToManyField('Student')

    def __str__(self):
        return self.name

class Task(models.Model):
    task = models.CharField(max_length=20)
    status = models.CharField(max_length=20)
    description = models.CharField(max_length=20)
    date = models.DateField()

world_books/WebBooks/catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import SelectDateWidget

from .models import Task


class FormTask(forms.ModelForm):
    task = forms.CharField(max_length=20)
    status = forms.CharField(max_length=20)
    description = forms.CharField(max_length=20)
    date = forms.DateField(label='Срок:')
    class Meta:
        model = Task
        fields = ['task', 'status', 'description', 'date']

world_books/WebBooks/catalog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .forms import FormTask
from .models import Lecturer, Book, BookInstance, Author, Group, Student, Task
from django.views import generic


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact=2).count()
    num_authors = Author.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    return render(request, 'index.html', context={'num_books':num_books,
                                                  'num_instances':num_instances,
                                                  'num_instances_available': num_instances_available,
                                                  'num_authors': num_authors,
                                                  'num_visits': num_visits,
                                                  }
                  )

def index2(request):
    group = Group.objects.all()
    students = group.students_set.all()
    courses = group.course_set.all()
    lecturer = Lecturer.objects.all()
    return render(request, "index2.html", {"group": group, "students": students, "courses": courses})


def add_task(request):
    tasks = Task.objects.all()
    if request.method == "POST":
        form = FormTask(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            return redirect('/')
    else:
        form = FormTask()
        return render(request, "add_task.html", {"form": form, "tasks": tasks})

def edit_task(request, task_id):
    tasks = Task.objects.get(id=task_id)
    if request.method == "POST":
        form = FormTask(request.POST, instance=tasks)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = FormTask(instance=tasks)
        return render(request, "edit_task.html", {"form": form, "tasks": tasks})

def delete_task(request, task_id):
    tasks = Task.objects.get(id=task_id)
    if request.method == "POST":
        tasks.delete()
        return redirect('/')
    else:
        return render(request, "delete_task.html", {"tasks": tasks})

class BookListView(generic.ListView):
    model = Book
    paginate_by = 2

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 2

world_books/WebBooks/catalog/templates/add_task.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Information</title>
</head>
<body>
    <h1>Мои задачи</h1>
    <div class="div">
    <form method="POST">
        {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input class = "btn1" type = "submit" value="Добавить задачу">
    </form>
    </div>
    <table style = "border: 3px solid black; border-collapse: collapse; border: 1px solid black;">
        <tr>
            <td style="padding: 10px 20px; text-align: center; border: 2px solid black;">Задание</td>
            <td style="padding: 10px 20px; text-align: center; border: 2px solid black;">Статус</td>
            <td style="padding: 10px 20px; text-align: center; border: 2px solid black;">Описание</td>
            <td style="padding: 10px 20px; text-align: center; border: 2px solid black;">Срок</td>
        </tr>
        {% for task in tasks %}
        <tr>
            <td style="padding: 10px 20px; text-align: center; border: 2px solid black;">{{task.task}}</td>
            <td style="padding: 10px 20px; text-align: center; border: 2px solid black;">{{task.status}}</td>
            <td style="padding: 10px 20px; text-align: center; border: 2px solid black;">{{task.description}}</td>
            <td style="padding: 10px 20px; text-align: center; border: 2nnpx solid black;">{{task.date}}</td>
            <td>
                <a class = "btn2" href="{% url 'edit_task' task.id %}">Редактировать</a>
                <a class = "btn2" href="{% url 'delete_task' task.id %}">Удалить</a>
            </td>
        </tr>
        {% endfor %}
    </table>
</body>

world_books/WebBooks/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Мир книг</title>{% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,
                                   initial-scale=1">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Добавление статического СSS-файла -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block head %}
    <img src="{% static 'images/logotip.png' %}"
         style="width:1OOpx; height:1OOpx;"
         align="middle">
    <font size="7">Сайт "Мир книг"</font>
    {% endblock %}
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
            <ul class="sidebar-nav">
                <li><a href="{% url 'index' %}">Главная страница</a></li>
                <li><a href="{% url 'books' %}">Все книги</a></li>
                <li><a href="{% url 'author' %}">Все авторы</a></li>
            </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10">
            {% block content %}{% endblock %}
            {% block pagination %}
                {% if is_paginated %}
                    <div class = "pagination">

                        <span class="page-links">
                                {% if page_obj.has_previous %}
                                    <a href="{{request.path}}?page={{page_obj.previous_page_number}}">
                                        Предыдущая
                                    </a>
                                {% endif %}
                                <span class="page-current">
                                    Страница {{page_obj.number}} из
                                        {{page_obj.paginator.num_pages}}.
                                </span>
                                {% if page_obj.has_next %}
                            <a href="{{request.path}}?page={{page_obj.next_page_number}}">
                                Следующая
                            </a>
                        {% endif %}
                        </span>
                    </div>
        {% endif %}
    {% endblock %}


            {% block footer %}
                {% block copyright %}
                    <p>Copyright ItMouse.by</p>
                {% endblock %}
            {% endblock %}
        </div>
    </div>
</div>
{% block sidebar %}
<ul class="sidebar-nav">
    <li><a href="{% url 'index' %}"></a></li>
    <li><a href="{% url 'books' %}"></a></li>
    <li><a href="{% url 'authors' %}"></a></li>
</ul>
{% endblock %}
{% if user.is_authenticated %}
<p>Вы {{user.first_name}}</p>
<form id = "logout-form" method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <button type = "submit">Выход</button>
</form>
{% endif %}
</body>
</html>

world_books/WebBooks/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}
    {% block content %}
    <h1>Список авторов в БД</h1>
    {% if author_list %}
        {% for author in author_list.all %}
            <p>{{author.first_name}} {{author.last_name}},
            <strong>Родился-</strong>{{author.date_of_birth}},
            <strong>Умер-</strong>{{author.date_of_death}}</p>
        {% endfor %}
    {% else %}
        <p>В базе данных нет авторов</p>
    {% endif %}
    {% endblock %}

world_books/WebBooks/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}
{% block content %}
<h1>Название книги: {{book.title}}</h1>
<p><strong>Жанр:</strong>{{ book.genre }}</p>
<p><strong>Аннотация:</strong>{{ book.summary }}</p>
<p><strong>ISBN:</strong>{{ book.isbn }}</p>
<p><strong>Язык:</strong>{{ book.language }}</p>
    {% for author in book.author.all %}
    <p><strong>Автор:</strong>
        <a href="">{{ author.first_name }}
                   {{ author.last_name }}</a></p>
    {% endfor %}
<div style="margin-left: 20px; margin-top:20px;">
    <h4>Количество экземпляров книг в БД</h4>
    {% for copy in book.bookinstance_set.all %}
    <hr><p class="{% if copy.status == 1 %} text-success
                   {% elif copy.status == 1 %} text-danger
                   {% else %} text-warning
                   {% endif %}">{{copy.get_status_display}}</p>
    <p><strong>Издательство:</strong>{{copy.imprint}}</p>

    <p class="text-muted"><strong>Инвентарный номер</strong>{{copy.id}}</p>
    <p><strong>Статус экземпляра книги в БД:</strong>{{copy.status}}</p>
    {% endfor %}
</div>
{% endblock %}
<p><strong>Автор:</strong><a href = "">{{author.first_name}}
        {{author.last_name}}</a>
</p>

world_books/WebBooks/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}
{% block content %}
<h1>Список книг в БД</h1>
{% if book_list %}
<ul>
    {% for book in book_list %}
    <li>
        <a href="{{ book.get_absolute_url }}">
            {{book.title}}</a>
        ( {{book.genre }} )
    </li>
    {% endfor %}
</ul>
{% else %}
<p>В базе данных нет книг</p>
{% endif %}
<div style="margin-left:20px;
            margin-top:20px;">
    <h4>Количество экземпляров книг в БД</h4>
    {% for copy in book.bookinstance_set.all %}
</div>
{% endfor %}
{% endblock %}

world_books/WebBooks/catalog/templates/delete_task.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
    <div class = "container">
      <h1>Удалить задачу</h1>
      <p>Удалить задачу "<strong>{{ tasks.task }}</strong>"?</p>
      <p>Статус: {{ tasks.status }}</p>
      <p>Описание: {{ tasks.description }}</p>
      <p>Дата: {{ tasks.date }}</p>
      <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn1">Удалить</button>
        <a class="btn2" href="{% url 'add_task' %}" class="button cancel-button">Отмена</a>
      </form>
    </div>
</body>
</html>

world_books/WebBooks/catalog/templates/edit_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="container">
        <form method="POST">
          <h1>Редактировать задачу</h1>
          {% csrf_token %}
          {{ form.as_p }}
          <button class = "btn1" type="submit">Сохранить изменения</button>
        </form>
        <a class = "btn2" href="{% url 'add_task' %}">Назад к списку</a>
    </div>
</body>
</html>

world_books/WebBooks/catalog/templates/index.html
{% extends "base_generic.html" %}
{% block content %}
<h1>Главная страница</h1>
<p>Добро пожаловать в <em>Мир книг</em>, Это очень простой
    веб-сайт, написанный на Django. Разработан на Python
    в качестве учебного примера с использованием PyCharm.</p>
<h2>Динамический контент</h2>
<p>База данных сайта Мир книг содержит следующее
    количество записей :</p>
<ul>
    <li><strong>Koличecтвo книг:</strong> {{ num_books }}</li>
    <li><strong>Koличecтвo экземпляров книг:</strong> {{ num_instances }}</li>
    <li><strong>Koличecтвo экземпляров книг в заказе:</strong> {{ num_instances_available }}</li>
    <li><strong>Koличecтвo авторов книг:</strong> {{ num_authors }}</li>
</ul>
<p>Количество посещений данной страницы - {{num_visits}}</p>
{% endblock %}

world_books/WebBooks/catalog/templates/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>